package binance

import "time"

const BINANCE_REQUEST_STATUS_SUCCESS = "SUCCESS"
const BINANCE_REQUEST_STATUS_FAIL = "FAIL"
const ORDER_EXPIRE_TIME = time.Minute * 5 // 5 mins

const BASE_URL = "https://bpay.binanceapi.com"
const CREATE_ORDER_PATH = "/binancepay/openapi/v2/order"
const QUERY_ORDER_PATH = "/binancepay/openapi/v2/order/query"
const CREATE_PAYOUT_PATH = "/binancepay/openapi/payout/transfer"

const BINANCE_TRANSFER_TYPE_MERCHANT_PAYMENT = "MERCHANT_PAYMENT"
const BINANCE_TRANSFER_TYPE_REIMBURSEMENT = "REIMBURSEMENT"
const BINANCE_TRANSFER_TYPE_OTHERS = "OTHERS"

const BINANCE_RECEIVE_TYPE_PAY_ID = "PAY_ID"
const BINANCE_RECEIVE_TYPE_BINANCE_ID = "BINANCE_ID"

const BINANCE_TRANSFER_REMARK_PAYOUT = "Payout from Moniesto"
const BINANCE_TRANSFER_REMARK_REFUND = "Refund from Moniesto"

const QUERY_ORDER_STATUS_INITIAL = "INITIAL"
const QUERY_ORDER_STATUS_PAID = "PAID"
const QUERY_ORDER_STATUS_EXPIRED = "EXPIRED"
const QUERY_ORDER_STATUS_PENDING = "PENDING"
const QUERY_ORDER_STATUS_CANCELED = "CANCELED"
const QUERY_ORDER_STATUS_ERROR = "ERROR"
const QUERY_ORDER_STATUS_REFUNDING = "REFUNDING"
const QUERY_ORDER_STATUS_REFUNDED = "REFUNDED"
