// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: binance_payment_transaction.sql

package db

import (
	"context"
)

const createBinancePaymentTransactions = `-- name: CreateBinancePaymentTransactions :one
INSERT INTO "binance_payment_transaction" (
        id,
        qrcode_link,
        checkout_link,
        deep_link,
        universal_link,
        status,
        user_id,
        moniest_id,
        date_type,
        date_value,
        moniest_fee,
        amount,
        webhook_url,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        now(),
        now()
    )
RETURNING id, qrcode_link, checkout_link, deep_link, universal_link, status, user_id, moniest_id, date_type, date_value, moniest_fee, amount, webhook_url, payer_id, created_at, updated_at
`

type CreateBinancePaymentTransactionsParams struct {
	ID            string                 `json:"id"`
	QrcodeLink    string                 `json:"qrcode_link"`
	CheckoutLink  string                 `json:"checkout_link"`
	DeepLink      string                 `json:"deep_link"`
	UniversalLink string                 `json:"universal_link"`
	Status        BinancePaymentStatus   `json:"status"`
	UserID        string                 `json:"user_id"`
	MoniestID     string                 `json:"moniest_id"`
	DateType      BinancePaymentDateType `json:"date_type"`
	DateValue     int32                  `json:"date_value"`
	MoniestFee    float64                `json:"moniest_fee"`
	Amount        float64                `json:"amount"`
	WebhookUrl    string                 `json:"webhook_url"`
}

func (q *Queries) CreateBinancePaymentTransactions(ctx context.Context, arg CreateBinancePaymentTransactionsParams) (BinancePaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, createBinancePaymentTransactions,
		arg.ID,
		arg.QrcodeLink,
		arg.CheckoutLink,
		arg.DeepLink,
		arg.UniversalLink,
		arg.Status,
		arg.UserID,
		arg.MoniestID,
		arg.DateType,
		arg.DateValue,
		arg.MoniestFee,
		arg.Amount,
		arg.WebhookUrl,
	)
	var i BinancePaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.QrcodeLink,
		&i.CheckoutLink,
		&i.DeepLink,
		&i.UniversalLink,
		&i.Status,
		&i.UserID,
		&i.MoniestID,
		&i.DateType,
		&i.DateValue,
		&i.MoniestFee,
		&i.Amount,
		&i.WebhookUrl,
		&i.PayerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
