// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: email_verification_token.sql

package db

import (
	"context"
	"time"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO "email_verification_token" (
        id,
        user_id,
        token,
        token_expiry,
        deleted,
        created_at
    )
VALUEs ($1, $2, $3, $4, false, now())
RETURNING id, user_id, token, token_expiry, deleted, created_at
`

type CreateEmailVerificationTokenParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Token       string    `json:"token"`
	TokenExpiry time.Time `json:"token_expiry"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.TokenExpiry,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.TokenExpiry,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationTokenByToken = `-- name: DeleteEmailVerificationTokenByToken :exec
UPDATE "email_verification_token"
SET deleted = true
WHERE "token" = $1
`

func (q *Queries) DeleteEmailVerificationTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerificationTokenByToken, token)
	return err
}

const deleteEmailVerificationTokenByUserID = `-- name: DeleteEmailVerificationTokenByUserID :exec
UPDATE "email_verification_token"
SET deleted = true
WHERE "user_id" = $1
`

func (q *Queries) DeleteEmailVerificationTokenByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerificationTokenByUserID, userID)
	return err
}

const getEmailVerificationTokenByToken = `-- name: GetEmailVerificationTokenByToken :one
SELECT id, user_id, token, token_expiry, deleted, created_at
FROM "email_verification_token"
WHERE "token" = $1
    AND "deleted" = false
`

func (q *Queries) GetEmailVerificationTokenByToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationTokenByToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.TokenExpiry,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}
