// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: feedback.sql

package db

import (
	"context"
	"database/sql"
)

const createFeedback = `-- name: CreateFeedback :exec
INSERT INTO "feedback" (
        id,
        user_id,
        type,
        message,
        solved,
        created_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        false,
        now()
    )
`

type CreateFeedbackParams struct {
	ID      string         `json:"id"`
	UserID  sql.NullString `json:"user_id"`
	Type    sql.NullString `json:"type"`
	Message string         `json:"message"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, createFeedback,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Message,
	)
	return err
}
