// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"fmt"
	"time"
)

type ImageType string

const (
	ImageTypeProfilePhoto    ImageType = "profile_photo"
	ImageTypeBackgroundPhoto ImageType = "background_photo"
)

func (e *ImageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageType(s)
	case string:
		*e = ImageType(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageType: %T", src)
	}
	return nil
}

// Stores single card data
type Card struct {
	ID        string         `json:"id"`
	Token     sql.NullString `json:"token"`
	Deleted   bool           `json:"deleted"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// Stores email verification token for verifying account
type EmailVerification struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Token       string    `json:"token"`
	TokenExpiry time.Time `json:"token_expiry"`
	CreatedAt   time.Time `json:"created_at"`
}

// Stores image data
type Image struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	Link          string    `json:"link"`
	ThumbnailLink string    `json:"thumbnail_link"`
	Type          ImageType `json:"type"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Stores moniest data
type Moniest struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Bio         sql.NullString `json:"bio"`
	Description sql.NullString `json:"description"`
	Score       float64        `json:"score"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Stores relation between moniest and card
type MoniestCard struct {
	MoniestID string `json:"moniest_id"`
	CardID    string `json:"card_id"`
}

// Stores reset token for forget password operations
type PasswordResetToken struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Token       string    `json:"token"`
	TokenExpiry time.Time `json:"token_expiry"`
	CreatedAt   time.Time `json:"created_at"`
}

type Post struct {
	ID        string    `json:"id"`
	MoniestID string    `json:"moniest_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Stores subscription data of a moniest
type SubscriptionInfo struct {
	ID        string    `json:"id"`
	MoniestID string    `json:"moniest_id"`
	Fee       float64   `json:"fee"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Stores user data
type User struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Surname       string         `json:"surname"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	EmailVerified bool           `json:"email_verified"`
	Password      string         `json:"password"`
	Location      sql.NullString `json:"location"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Stores relation between user and card
type UserCard struct {
	UserID string `json:"user_id"`
	CardID string `json:"card_id"`
}

// Stores user subscription info
type UserSubscription struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	MoniestID string    `json:"moniest_id"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}
