// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: moniest_post_statistics.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createMoniestPostCryptoStatistics = `-- name: CreateMoniestPostCryptoStatistics :one
INSERT INTO moniest_post_crypto_statistics (
        "id",
        "moniest_id",
        "pnl_7days",
        "roi_7days",
        "win_rate_7days",
        "posts_7days",
        "pnl_30days",
        "roi_30days",
        "win_rate_30days",
        "posts_30days",
        "pnl_total",
        "roi_total",
        "win_rate_total",
        "created_at"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        now()
    )
RETURNING id, moniest_id, pnl_7days, roi_7days, win_rate_7days, posts_7days, pnl_30days, roi_30days, win_rate_30days, posts_30days, pnl_total, roi_total, win_rate_total, created_at, updated_at
`

type CreateMoniestPostCryptoStatisticsParams struct {
	ID            string          `json:"id"`
	MoniestID     string          `json:"moniest_id"`
	Pnl7days      sql.NullFloat64 `json:"pnl_7days"`
	Roi7days      sql.NullFloat64 `json:"roi_7days"`
	WinRate7days  sql.NullFloat64 `json:"win_rate_7days"`
	Posts7days    []string        `json:"posts_7days"`
	Pnl30days     sql.NullFloat64 `json:"pnl_30days"`
	Roi30days     sql.NullFloat64 `json:"roi_30days"`
	WinRate30days sql.NullFloat64 `json:"win_rate_30days"`
	Posts30days   []string        `json:"posts_30days"`
	PnlTotal      sql.NullFloat64 `json:"pnl_total"`
	RoiTotal      sql.NullFloat64 `json:"roi_total"`
	WinRateTotal  sql.NullFloat64 `json:"win_rate_total"`
}

func (q *Queries) CreateMoniestPostCryptoStatistics(ctx context.Context, arg CreateMoniestPostCryptoStatisticsParams) (MoniestPostCryptoStatistic, error) {
	row := q.db.QueryRowContext(ctx, createMoniestPostCryptoStatistics,
		arg.ID,
		arg.MoniestID,
		arg.Pnl7days,
		arg.Roi7days,
		arg.WinRate7days,
		pq.Array(arg.Posts7days),
		arg.Pnl30days,
		arg.Roi30days,
		arg.WinRate30days,
		pq.Array(arg.Posts30days),
		arg.PnlTotal,
		arg.RoiTotal,
		arg.WinRateTotal,
	)
	var i MoniestPostCryptoStatistic
	err := row.Scan(
		&i.ID,
		&i.MoniestID,
		&i.Pnl7days,
		&i.Roi7days,
		&i.WinRate7days,
		pq.Array(&i.Posts7days),
		&i.Pnl30days,
		&i.Roi30days,
		&i.WinRate30days,
		pq.Array(&i.Posts30days),
		&i.PnlTotal,
		&i.RoiTotal,
		&i.WinRateTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
