// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: post_crypto.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO "post_crypto" (
        id,
        moniest_id,
        currency,
        start_price,
        duration,
        target1,
        target2,
        target3,
        stop,
        direction,
        score,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        now(),
        now()
    )
RETURNING id, moniest_id, currency, start_price, duration, target1, target2, target3, stop, direction, score, finished, deleted, created_at, updated_at
`

type CreatePostParams struct {
	ID         string          `json:"id"`
	MoniestID  string          `json:"moniest_id"`
	Currency   string          `json:"currency"`
	StartPrice float64         `json:"start_price"`
	Duration   time.Time       `json:"duration"`
	Target1    float64         `json:"target1"`
	Target2    sql.NullFloat64 `json:"target2"`
	Target3    sql.NullFloat64 `json:"target3"`
	Stop       sql.NullFloat64 `json:"stop"`
	Direction  EntryPosition   `json:"direction"`
	Score      float64         `json:"score"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (PostCrypto, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.MoniestID,
		arg.Currency,
		arg.StartPrice,
		arg.Duration,
		arg.Target1,
		arg.Target2,
		arg.Target3,
		arg.Stop,
		arg.Direction,
		arg.Score,
	)
	var i PostCrypto
	err := row.Scan(
		&i.ID,
		&i.MoniestID,
		&i.Currency,
		&i.StartPrice,
		&i.Duration,
		&i.Target1,
		&i.Target2,
		&i.Target3,
		&i.Stop,
		&i.Direction,
		&i.Score,
		&i.Finished,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
