// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: post_crypto_description.sql

package db

import (
	"context"
)

const addPostDescription = `-- name: AddPostDescription :one
INSERT INTO "post_crypto_description" (
        id,
        post_id,
        description,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, now(), now())
RETURNING id, post_id, description, created_at, updated_at
`

type AddPostDescriptionParams struct {
	ID          string `json:"id"`
	PostID      string `json:"post_id"`
	Description string `json:"description"`
}

func (q *Queries) AddPostDescription(ctx context.Context, arg AddPostDescriptionParams) (PostCryptoDescription, error) {
	row := q.db.QueryRowContext(ctx, addPostDescription, arg.ID, arg.PostID, arg.Description)
	var i PostCryptoDescription
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
