// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: subscription_info.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscriptionInfo = `-- name: CreateSubscriptionInfo :one
INSERT INTO subscription_info 
    (id, 
    moniest_id, 
    fee, 
    message, 
    created_at) 
VALUES
    ($1, $2, $3, $4, now())
RETURNING id, moniest_id, fee, message, deleted, created_at, updated_at
`

type CreateSubscriptionInfoParams struct {
	ID        string         `json:"id"`
	MoniestID string         `json:"moniest_id"`
	Fee       float64        `json:"fee"`
	Message   sql.NullString `json:"message"`
}

func (q *Queries) CreateSubscriptionInfo(ctx context.Context, arg CreateSubscriptionInfoParams) (SubscriptionInfo, error) {
	row := q.db.QueryRowContext(ctx, createSubscriptionInfo,
		arg.ID,
		arg.MoniestID,
		arg.Fee,
		arg.Message,
	)
	var i SubscriptionInfo
	err := row.Scan(
		&i.ID,
		&i.MoniestID,
		&i.Fee,
		&i.Message,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
